//! Cross-engine differential vs **KosherJava** (ADR core-domain/0003/0008, /0017). KosherJava is an
//! independent zmanim engine (NOAA solar calculator) — a non-circular cross-check distinct from the
//! Wolfram astronomy oracle and the Hebcal/MyZmanim calendar oracles (open-decisions #9's
//! "+ zmanim-core cross-check"). Its sea-level sunrise/sunset (zenith 90.833° = geometric sun-center
//! at −0.8333°) is matched by our `DepressionAngle{0.8333°, geometric}`, so the comparison isolates
//! the **solar-position algorithm** (no horizon/elevation/refraction convention skew).
//!
//! The reference values are committed (`tests/fixtures/kosherjava_vectors.csv`, generated by
//! `tools/KosherDiff.java`) — same oracle-as-fixture pattern as the Wolfram golden vectors; the LGPL
//! jar is a build-tool, never vendored, never shipped. No runtime Java dependency.

use core_engine::events::{read_instant, Bound, Direction, PrimBound, ReadSpec};
use core_engine::params::Optics;
use core_engine::time::jd_from_gregorian;
use core_engine::Site;

const FIXTURE: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/tests/fixtures/kosherjava_vectors.csv"
);
/// KosherJava (NOAA) vs our F1 series at the horizon: a few-second-class difference is expected.
const TOL_MS: i64 = 30_000;

fn our_millis(site: &Site, y: i32, m: u8, d: u8, dir: Direction, optics: &Optics) -> Option<i64> {
    let ref_jd = jd_from_gregorian(y, m as u32, d as f64 + 0.5) - site.lon_deg / 360.0;
    read_instant(
        site,
        ref_jd,
        ReadSpec::DepressionAngle {
            angle_deg: 0.833_3,
            dir,
        },
        optics,
    )
    .map(|a| a.unix_nanos / 1_000_000)
}

/// Our literal-72-minute MGA sof-zman-shma (ADR core-domain/0021): 3 proportional hours into the day
/// bounded by alos = sunrise−72 and tzais = sunset+72 FIXED clock minutes. We base it on
/// `Depression{0.8333°}` (= KosherJava's sea-level sunrise/sunset basis) so the comparison isolates the
/// new `OffsetMinutes`-bounded proportional read, matching the sunrise/sunset differential above.
fn our_mga72_millis(site: &Site, y: i32, m: u8, d: u8, optics: &Optics) -> Option<i64> {
    let ref_jd = jd_from_gregorian(y, m as u32, d as f64 + 0.5) - site.lon_deg / 360.0;
    read_instant(
        site,
        ref_jd,
        ReadSpec::Proportional {
            fraction: 0.25,
            start: Bound::OffsetMinutes {
                base: PrimBound::Depression {
                    angle_deg: 0.833_3,
                    dir: Direction::Rising,
                },
                offset_min: -72.0,
            },
            end: Bound::OffsetMinutes {
                base: PrimBound::Depression {
                    angle_deg: 0.833_3,
                    dir: Direction::Setting,
                },
                offset_min: 72.0,
            },
        },
        optics,
    )
    .map(|a| a.unix_nanos / 1_000_000)
}

#[test]
fn cross_engine_sof_zman_shma_mga72_vs_kosherjava() {
    let data = std::fs::read_to_string(FIXTURE).expect("kosherjava fixture present");
    let optics = Optics::default(); // geometric sun-center (matches KJ's 90.833° zenith basis)
    let (mut pass, mut fail, mut max_res) = (0u32, 0u32, 0i64);
    let mut out: Vec<String> = Vec::new();

    for line in data.lines().skip(1) {
        if line.trim().is_empty() {
            continue;
        }
        let f: Vec<&str> = line.split(',').collect();
        let (name, lat, lon) = (f[0], f[1].parse().unwrap(), f[2].parse().unwrap());
        let dp: Vec<&str> = f[3].split('-').collect();
        let (y, m, d): (i32, u8, u8) = (
            dp[0].parse().unwrap(),
            dp[1].parse().unwrap(),
            dp[2].parse().unwrap(),
        );
        let site = Site {
            lat_deg: lat,
            lon_deg: lon,
            elev_m: 0.0,
        };
        let kj = f[6]; // sofzman_mga72_millis
        let ours = our_mga72_millis(&site, y, m, d, &optics);
        match (kj, ours) {
            ("null", None) => pass += 1,
            ("null", Some(_)) | (_, None) => {
                fail += 1;
                out.push(format!(
                    "!! {name} {y}-{m}-{d} sofzman_mga72: occurrence mismatch (kj={kj}, ours={ours:?})"
                ));
            }
            (k, Some(o)) => {
                let res = o - k.parse::<i64>().unwrap();
                max_res = max_res.max(res.abs());
                if res.abs() <= TOL_MS {
                    pass += 1;
                } else {
                    fail += 1;
                    out.push(format!(
                        "!! {name} {y}-{m}-{d} sofzman_mga72: {res} ms (> {TOL_MS})"
                    ));
                }
            }
        }
    }
    for r in &out {
        eprintln!("{r}");
    }
    eprintln!(
        "cross-engine MGA-72 sof-zman-shma vs KosherJava: {pass} ok, {fail} fail; max |residual| = {max_res} ms (tol {TOL_MS})"
    );
    assert_eq!(
        fail, 0,
        "{fail} MGA-72 row(s) diverged from KosherJava beyond tolerance"
    );
}

#[test]
fn cross_engine_sunrise_sunset_vs_kosherjava() {
    let data = std::fs::read_to_string(FIXTURE).expect("kosherjava fixture present");
    let optics = Optics::default(); // depression_refraction = None → geometric sun-center
    let (mut pass, mut fail, mut max_res) = (0u32, 0u32, 0i64);
    let mut out: Vec<String> = Vec::new();

    for line in data.lines().skip(1) {
        if line.trim().is_empty() {
            continue;
        }
        let f: Vec<&str> = line.split(',').collect();
        let (name, lat, lon) = (f[0], f[1].parse().unwrap(), f[2].parse().unwrap());
        let dp: Vec<&str> = f[3].split('-').collect();
        let (y, m, d) = (
            dp[0].parse().unwrap(),
            dp[1].parse().unwrap(),
            dp[2].parse().unwrap(),
        );
        let site = Site {
            lat_deg: lat,
            lon_deg: lon,
            elev_m: 0.0,
        };
        for (col, dir, label) in [
            (4usize, Direction::Rising, "sunrise"),
            (5, Direction::Setting, "sunset"),
        ] {
            let kj = f[col];
            let ours = our_millis(&site, y, m, d, dir, &optics);
            match (kj, ours) {
                ("null", None) => pass += 1,
                ("null", Some(_)) | (_, None) => {
                    fail += 1;
                    out.push(format!("!! {name} {y}-{m}-{d} {label}: occurrence mismatch (kj={kj}, ours={ours:?})"));
                }
                (k, Some(o)) => {
                    let res = o - k.parse::<i64>().unwrap();
                    max_res = max_res.max(res.abs());
                    if res.abs() <= TOL_MS {
                        pass += 1;
                    } else {
                        fail += 1;
                        out.push(format!(
                            "!! {name} {y}-{m}-{d} {label}: {res} ms (> {TOL_MS})"
                        ));
                    }
                }
            }
        }
    }
    for r in &out {
        eprintln!("{r}");
    }
    eprintln!(
        "cross-engine vs KosherJava: {pass} ok, {fail} fail; max |residual| = {max_res} ms (tol {TOL_MS})"
    );
    assert_eq!(
        fail, 0,
        "{fail} row(s) diverged from KosherJava beyond tolerance"
    );
}
